### SITE
GET http://localhost:3330/


### REGISTER
POST http://localhost:3330/api/v1/auth/register
Content-Type: application/json

{
    "name": "drhappykuntqn",
    "email": "drhappykun.tqn@gmail.com",
    "password": "123456",
    "passwordConfirm": "123456"
}


### LOGIN
POST http://localhost:3330/api/v1/auth/login
Content-Type: application/json

{
    "email": "drhappykun.tqn@gmail.com",
    "password": "123456"
}


### LOGOUT
DELETE http://localhost:3330/api/v1/auth/logout
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Njg1MDk3N2EzNjEyZTM0ODg3Y2NlNGEiLCJuYW1lIjoidHFuZ3V5ZW4xOWl0M3ZrdSIsImVtYWlsIjoidHFuZ3V5ZW4uMTlpdDNAdmt1LnVkbi52biIsImlhdCI6MTcxOTk5NDg1OCwiZXhwIjoxNzE5OTk1NDU4fQ.JCjFdrcNPtEybRcsc9IUYimsk9iN6jz28NzwBk8soXE"
}


### REFRESH TOKEN
POST http://localhost:3330/api/v1/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Njg0Y2Q2Y2ZlNjk0MmY1ZWE2MzI4ZDgiLCJuYW1lIjoiZHJoYXBweWt1biIsImVtYWlsIjoiZHJoYXBweWt1bjFAZ21haWwuY29tIiwiaWF0IjoxNzE5OTg3NTQ2LCJleHAiOjE3MTk5ODc2NjZ9.AgY4wzKv5vPf07wnENRd2uxXbHwImjYDq0uv9aoblKA"
}


###
PUT http://localhost:3330/api/v1/auth/change-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Njg1MTBjOWFiZDI2MjIxYWQzNTA3ODgiLCJuYW1lIjoiZHJoYXBweWt1bnRxbiIsImVtYWlsIjoiZHJoYXBweWt1bi50cW5AZ21haWwuY29tIiwiaWF0IjoxNzE5OTk4NzQzLCJleHAiOjE3MTk5OTkwNDN9.6nB9eRKVXyad3Kp915E2ad0Jgmj3701dvQgilbfhqkY

{
    "currentPassword": "vJ0pRDrt",
    "newPassword": "123456",
    "passwordConfirm": "123456"
}


###
POST http://localhost:3330/api/v1/auth/forgot-password
Content-Type: application/json

{
    "email": "drhappykun.tqn@gmail.com"
}


### AUTH GOOGLE
POST http://localhost:3330/api/v1/auth/google
Content-Type: application/json

{
    "access_token": "ya29.a0AXooCguiGzYw0Spm3KsKqJpoCOw5l-5Rqe9tmJsJ9r9f6-iFtKBsDsIqwCd-t7xxvRp1RmVYXYCI58VJ9s0hbQRx5fkKQwEk3WkTo_0nDeMRkS4PKsUmQuncze6eOfxqbTJRV0E0_j4KaJr0QFw-3LMGgN-CoRtE0nW9aCgYKASgSARASFQHGX2MiF4BAWBsDYyVbuAixw8PqOQ0171"
}


### GET LIST USER BY ADMIN
GET http://localhost:3330/api/v1/auth/get-user-list
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Njg1MTBjOWFiZDI2MjIxYWQzNTA3ODgiLCJuYW1lIjoiZHJoYXBweWt1bnRxbiIsImVtYWlsIjoiZHJoYXBweWt1bi50cW5AZ21haWwuY29tIiwiaWF0IjoxNzE5OTk4OTQ2LCJleHAiOjE3MTk5OTkyNDZ9.qicUody4G5zEr3rGcCvVUnsVea7-hEoYj-dRyvwvEyg